using System;
using System.IO;
using UnityEngine;

namespace Covyne.CADET.Editor.Mac
{
    /// <summary>
    /// Helper class for reading and writing macOS credentials to ~/.env_cadet_mac_creds
    /// </summary>
    public static class MacCredentialsHelper
    {
        private const string CREDENTIALS_FILE_NAME = ".env_cadet_mac_creds";
        
        /// <summary>
        /// Gets the full path to the credentials file in the user's home directory
        /// </summary>
        public static string GetCredentialsFilePath()
        {
            string homeDir = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
            return Path.Combine(homeDir, CREDENTIALS_FILE_NAME);
        }
        
        /// <summary>
        /// Checks if credentials file exists
        /// </summary>
        public static bool CredentialsFileExists()
        {
            return File.Exists(GetCredentialsFilePath());
        }
        
        /// <summary>
        /// Reads the generated password (GEN_PW) from the file
        /// </summary>
        public static string ReadGeneratedPassword()
        {
            string filePath = GetCredentialsFilePath();
            
            if (!File.Exists(filePath))
            {
                return null;
            }
            
            try
            {
                string[] lines = File.ReadAllLines(filePath);
                
                foreach (string line in lines)
                {
                    string trimmedLine = line.Trim();
                    if (string.IsNullOrEmpty(trimmedLine) || trimmedLine.StartsWith("#"))
                        continue;
                    
                    // Parse KEY=VALUE format
                    int equalsIndex = trimmedLine.IndexOf('=');
                    if (equalsIndex > 0)
                    {
                        string key = trimmedLine.Substring(0, equalsIndex).Trim();
                        string value = trimmedLine.Substring(equalsIndex + 1).Trim();
                        
                        // Remove quotes if present
                        if (value.StartsWith("\"") && value.EndsWith("\""))
                        {
                            value = value.Substring(1, value.Length - 2);
                        }
                        
                        if (key.Equals("GEN_PW", StringComparison.OrdinalIgnoreCase))
                        {
                            return value;
                        }
                    }
                }
                
                return null;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[CADET] Failed to read macOS credentials: {ex.Message}");
                return null;
            }
        }
        
        /// <summary>
        /// Writes the generated password (GEN_PW) to the file
        /// </summary>
        public static bool WriteGeneratedPassword(string password)
        {
            if (string.IsNullOrEmpty(password))
            {
                Debug.LogError("[CADET] Cannot write empty password");
                return false;
            }
            
            string filePath = GetCredentialsFilePath();
            
            try
            {
                var lines = new System.Collections.Generic.List<string>();
                lines.Add("# CADET macOS Credentials");
                lines.Add("# This file is automatically generated. Do not edit manually.");
                lines.Add("");
                lines.Add($"GEN_PW={password}");
                
                // Write file with Unix line endings (LF only) to avoid bash warnings when sourcing
                File.WriteAllText(filePath, string.Join("\n", lines) + "\n");
                
                // Set file permissions to user-only (600 on Unix)
                // On Windows, this is handled by the file system
                #if UNITY_EDITOR_WIN
                // Windows doesn't need explicit permission setting
                #else
                try
                {
                    System.Diagnostics.Process.Start("chmod", $"600 \"{filePath}\"");
                }
                catch
                {
                    // Ignore if chmod fails
                }
                #endif
                
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[CADET] Failed to write macOS credentials: {ex.Message}");
                return false;
            }
        }
        
        /// <summary>
        /// Deletes the credentials file
        /// </summary>
        public static bool DeleteCredentials()
        {
            string filePath = GetCredentialsFilePath();
            
            if (!File.Exists(filePath))
            {
                return true; // Already deleted
            }
            
            try
            {
                File.Delete(filePath);
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[CADET] Failed to delete macOS credentials: {ex.Message}");
                return false;
            }
        }
    }
}

